Replace android.hardware.graphics.common-V4-ndk with android.hardware.graphics.common-V5-ndk
error: vendor/xiaomi/miuicamera-rubyx/Android.bp:28:1: module
"libcamera_ispinterface_jni.xiaomi" variant
"android_arm64_armv8-2a-dotprod_static": depends on multiple versions of
the same aidl_interface: android.hardware.graphics.common-V4-ndk-source,
android.hardware.graphics.common-V5-ndk-source

libgui dependencies and co use android.hardware.graphics.common-V5-ndk
while
vendor.mediatek.hardware.camera.isphal-V1-ndk uses
android.hardware.graphics.common-V4-ndk.

Luckily enough for us the changes from V4 -> V5 are benign, so just
replace the dependency.

Change-Id: I57da3c43b694c84fb4be9cf1543fa15c3b314a4a